AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic
  
  VpcId:
    Type: String
    Description: VpcId of the VPC where to install PN-CORE

  VpcSubnets:
    Type: String
    Description: subnets where to install PN-CORE

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'
  
  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ConfidentialObjectsDynamoTableName:
    Type: String
    Description: 'Name of dynamodb table containing fake confidentials informations'

  ConfidentialObjectsDynamoTableArn:
    Type: String
    Description: 'ARN of dynamodb table containing fake confidentials informations'

  PDVTokenizerBasePath:
    Type: String
    Description: 'Path base di invocazione al servizio di tokenizer'

  PDVUserRegistryBasePath:
    Type: String
    Description: 'Path base di invocazione al servizio di user registry'

  PDVUserRegistryRateLimiterMillis:
    Type: Number
    Description: 'Periodo di aggiornamento in millisecondi del rate limiter per le API di user-registry'

  PDVUserRegistryRateLimiterNRequests:
    Type: Number
    Description: 'Numero richieste impostate nel rate limiter per le API di user-registry'

  PDVUserRegistryRateLimiterTimeoutMillis:
    Type: Number
    Description: 'Periodo di timeout in millisecondi nel rate limiter per le API di user-registry'

  SelfcarePgBasePath:
    Type: String
    Description: 'Path base di invocazione al servizio di SelfcarePg'

  SelfcarePgRateLimiterMillis:
    Type: Number
    Description: 'Periodo di aggiornamento in millisecondi del rate limiter per le API di SelfcarePg'

  SelfcarePgRateLimiterNRequests:
    Type: Number
    Description: 'Numero richieste impostate nel rate limiter per le API di SelfcarePg'

  SelfcarePgRateLimiterTimeoutMillis:
    Type: Number
    Description: 'Periodo di timeout in millisecondi nel rate limiter per le API di SelfcarePg'

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CacheExpireMinutes:
    Type: String
    Description: 'Cache expire in minuti'

  CacheMaxSize:
    Type: String
    Description: 'Cache dimensione massima'

  ConfidentialInfoLogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

  ConfidentialInfoCdcKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receives cdc'

  LogsToExternalBucketArn:
    Type: String
    Description: 'Logs Delivery stream to S3 ARN'

  LogsToExternalBucketAlarmArn:
    Type: String
    Description: 'Log delivery stream alarm ARN'

  CdcToExternalBucketArn:
    Type: String
    Description: 'Cdc Delivery stream to S3 ARN'

  CdcToExternalBucketAlarmArn:
    Type: String
    Description: 'Cdc delivery stream alarm ARN'

  PnDataVaultSecretArn:
    Type: String
    Description: Data Vault secret ARN

  # Heath Check parameters
  HealthCheckInterval:
    Description: Seconds between two health check
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: health check timeout seconds
    Type: Number
    Default: 5
  
  HealthyThresholdCount:
    Description: |
      The number of consecutive health checks successes required before considering 
      an unhealthy target healthy. 
    Type: Number
    Default: 5
  
  UnhealthyThresholdCount:
    Description: |
      The number of consecutive health check failures required before considering a target unhealthy. 
    Type: Number
    Default: 2

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 60
    Type: Number
    Description: minimum autoscaling number of tasks\

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingThreshold:
    Default: 70
    Type: String
  
  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: maximum autoscaling number of tasks

  CloudWatchMetricCron:
    Type: String
    Description: Cron for which you send the custom metric for PDV to CloudWatch

Resources:

  # PN-DataVault microservice
  DataVaultMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-data-vault-sep'
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        AutoscalingStrategy: REST-API
        AutoscalingThreshold: !Ref AutoscalingThreshold
        AutoscalingCheckPeriod: !Ref AutoscalingCheckPeriod
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        AutoscalingDataPointN: !Ref AutoscalingDataPointN
        AutoscalingDataPointM: !Ref AutoscalingDataPointM
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_DATA_VAULT_DYNAMODB_TABLE_NAME=${ConfidentialObjectsDynamoTableName}'
        ContainerEnvEntry3: !Sub 'PN_DATA_VAULT_CLIENT_TOKENIZER_BASEPATH=${PDVTokenizerBasePath}'
        ContainerEnvEntry4: !Sub 'PN_DATA_VAULT_CLIENT_USERREGISTRY_BASEPATH=${PDVUserRegistryBasePath}'
        ContainerEnvEntry5: !Sub 'PN_DATA_VAULT_CLIENT_SELFCAREPG_BASEPATH=${SelfcarePgBasePath}'
        ContainerEnvEntry6: !Sub 'PN_DATA_VAULT_CACHE_EXPIRE_AFTER_MINUTES=${CacheExpireMinutes}'
        ContainerEnvEntry7: !Sub 'PN_DATA_VAULT_CACHE_MAX_SIZE=${CacheMaxSize}'
        ContainerEnvEntry8: !Sub 'RESILIENCE4J_RATELIMITER_INSTANCES_PDV_RATE_LIMITER_LIMIT_REFRESH_PERIOD=${PDVUserRegistryRateLimiterMillis}'
        ContainerEnvEntry9: !Sub 'RESILIENCE4J_RATELIMITER_INSTANCES_PDV_RATE_LIMITER_LIMIT_FOR_PERIOD=${PDVUserRegistryRateLimiterNRequests}'
        ContainerEnvEntry10: !Sub 'RESILIENCE4J_RATELIMITER_INSTANCES_PDV_RATE_LIMITER_TIMEOUT_DURATION=${PDVUserRegistryRateLimiterTimeoutMillis}'
        ContainerEnvEntry11: !Sub 'RESILIENCE4J_RATELIMITER_INSTANCES_SELC_RATE_LIMITER_LIMIT_REFRESH_PERIOD=${SelfcarePgRateLimiterMillis}'
        ContainerEnvEntry12: !Sub 'RESILIENCE4J_RATELIMITER_INSTANCES_SELC_RATE_LIMITER_LIMIT_FOR_PERIOD=${SelfcarePgRateLimiterNRequests}'
        ContainerEnvEntry13: !Sub 'RESILIENCE4J_RATELIMITER_INSTANCES_SELC_RATE_LIMITER_TIMEOUT_DURATION=${SelfcarePgRateLimiterTimeoutMillis}'
        ContainerEnvEntry14: !Sub 'PN_DATA_VAULT_CLOUDWATCH_METRIC_CRON=${CloudWatchMetricCron}'
        ContainerSecret1: !Sub 'PN_DATA_VAULT_TOKENIZER_API_KEY_PF=${PnDataVaultSecretArn}:TokenizerApiKeyForPF:AWSCURRENT:'
        ContainerSecret2: !Sub 'PN_DATA_VAULT_USERREGISTRY_API_KEY_PF=${PnDataVaultSecretArn}:UserRegistryApiKeyForPF:AWSCURRENT:'
        ContainerSecret3: !Sub 'PN_DATA_VAULT_SELFCAREPG_API_KEY_PG=${PnDataVaultSecretArn}:SelfcareApiKeyForPG:AWSCURRENT:'
        MicroServiceSecretPrefix: pn-PersonalDataVault
        MappedPaths: '/datavault/*,/datavault-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref VpcSubnets
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        CloudwatchLogKinesisStreamArn: !Ref ConfidentialInfoLogsKinesisSourceStreamArn
        TaskRoleManagedPolicyArn: !Ref DataVaultyMicroserviceTaskManagedPolicy

  # Grant operational rights to PN-Delivery microservice
  DataVaultyMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ExecuteTransaction
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:TransactGetItems
              - dynamodb:TransactWriteItems
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource:
              - !Ref ConfidentialObjectsDynamoTableArn
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - cloudwatch:GetMetricStream
              - cloudwatch:GetMetricData
            Resource:
              - "*"

  ## Dashboard
  DataVaultMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-data-vault"
        DynamoDBTableNames: !Join 
          - ',' 
          - - !Ref ConfidentialObjectsDynamoTableName
        AlarmArns: !Join
          - ','
          - - !GetAtt DataVaultMicroservice.Outputs.FatalLogsMetricAlarmArn
        LogGroupsNames: !Join
          - ','
          - - !Sub '/ecs/${ProjectName}-data-vault-sep'
          
  InfraMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-infra"
        AlarmArns: !Join
          - ','
          - - !Ref LogsToExternalBucketAlarmArn
            - !Ref CdcToExternalBucketAlarmArn
        KinesisDataArns: !Join
          - ','
          - - !Ref ConfidentialInfoLogsKinesisSourceStreamArn
            - !Ref ConfidentialInfoCdcKinesisSourceStreamArn
        KinesisFirehoseArns: !Join
          - ','
          - - !Ref LogsToExternalBucketArn
            - !Ref CdcToExternalBucketArn
