AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  ConfidentialInfoCdcKinesisSourceStreamArn:
    Type: String
    Description: kinesis stream Arn for ConfidentialObject dynamo table

  ConfidentialInfoLogsKinesisSourceStreamArn:
    Type: String
    Description: kinesis stream Arn for ConfidentialObject log

  LogRetention:
    Type: Number
    Default: 14

Resources:

  PCKmsEncDecDynamoDataKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      EnableKeyRotation: true
      Description: A symmetric encryption KMS key AES-256-GCM
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  ConfidentialObjectsDynamoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-ConfidentialObjects'
      TimeToLiveSpecification:
        AttributeName: 'expiration'
        Enabled: true
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !Ref ConfidentialInfoCdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        KMSMasterKeyId: !Ref PCKmsEncDecDynamoDataKey
        SSEEnabled: true
        SSEType: KMS   
                
  PnDataVaultLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-data-vault-sep'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref ConfidentialInfoLogsKinesisSourceStreamArn

Outputs:

  PCKmsEncDecDynamoDataKeyARN:
    Description: Name of KMS Key for Dynamo encode/decode data
    Value: !Sub '${PCKmsEncDecDynamoDataKey.Arn}'

  ConfidentialObjectsDynamoTableName:
    Description: Name of dynamodb table containing fake confidentials informations
    Value: !Ref ConfidentialObjectsDynamoTable

  ConfidentialObjectsDynamoTableArn:
    Description: ARN of dynamodb table containing fake confidentials informations
    Value: !Sub '${ConfidentialObjectsDynamoTable.Arn}'

  ConfidentialInfoLogsKinesisSourceStreamArn:
    Description: 'Kinesis source Logs stream ARN'
    Value: !Sub '${ConfidentialInfoLogsKinesisSourceStreamArn}'
  
  EcsLogGroup:
    Value: !GetAtt PnDataVaultLogGroup.Outputs.LogGroupName