AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  ConfidentialInfoCdcKinesisSourceStreamArn:
    Type: String
    Description: kinesis stream Arn for ConfidentialObject dynamo table

  ConfidentialInfoLogsKinesisSourceStreamArn:
    Type: String
    Description: kinesis stream Arn for ConfidentialObject log

Resources:

  ConfidentialObjectsDynamoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-ConfidentialObjects'
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !Ref ConfidentialInfoCdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
                
Outputs:
  ConfidentialObjectsDynamoTableName:
    Description: Name of dynamodb table containing fake confidentials informations
    Value: !Ref ConfidentialObjectsDynamoTable

  ConfidentialObjectsDynamoTableArn:
    Description: ARN of dynamodb table containing fake confidentials informations
    Value: !Sub '${ConfidentialObjectsDynamoTable.Arn}'

  ConfidentialInfoLogsKinesisSourceStreamArn:
    Description: 'Kinesis source Logs stream ARN'
    Value: !Sub '${ConfidentialInfoLogsKinesisSourceStreamArn}'